"""getamano category catalog — 173 categories across 14 sectors.
Source: /docs/getamano-catalogo-categorias.md (Mayo 2026 v1.0)
License flag: 'red' (requires license/cert), 'yellow' (insurance recommended), 'green' (no special license).
"""

CATALOG = [
    # SECTOR 1 — Hogar y mantenimiento
    {"sector": "hogar", "slug": "limpieza-hogar", "name_es": "Limpieza del hogar", "name_en": "House Cleaning", "license": "green"},
    {"sector": "hogar", "slug": "limpieza-alfombras", "name_es": "Limpieza de alfombras", "name_en": "Carpet Cleaning", "license": "green"},
    {"sector": "hogar", "slug": "limpieza-ventanas", "name_es": "Limpieza de ventanas", "name_en": "Window Cleaning", "license": "green"},
    {"sector": "hogar", "slug": "limpieza-post-construccion", "name_es": "Limpieza post-construcción", "name_en": "Post-Construction Cleaning", "license": "green"},
    {"sector": "hogar", "slug": "limpieza-comercial", "name_es": "Limpieza comercial", "name_en": "Commercial Cleaning", "license": "green"},
    {"sector": "hogar", "slug": "organizacion-hogar", "name_es": "Organización del hogar", "name_en": "Home Organization", "license": "green"},
    {"sector": "hogar", "slug": "lavanderia", "name_es": "Lavandería a domicilio", "name_en": "Laundry Service", "license": "green"},
    {"sector": "hogar", "slug": "plomeria", "name_es": "Plomería", "name_en": "Plumbing", "license": "red"},
    {"sector": "hogar", "slug": "electricidad", "name_es": "Electricidad", "name_en": "Electrical", "license": "red"},
    {"sector": "hogar", "slug": "hvac", "name_es": "Aire acondicionado y calefacción", "name_en": "HVAC", "license": "red"},
    {"sector": "hogar", "slug": "techos", "name_es": "Techos / Roofing", "name_en": "Roofing", "license": "yellow"},
    {"sector": "hogar", "slug": "pintura-interior", "name_es": "Pintura interior", "name_en": "Interior Painting", "license": "green"},
    {"sector": "hogar", "slug": "pintura-exterior", "name_es": "Pintura exterior", "name_en": "Exterior Painting", "license": "green"},
    {"sector": "hogar", "slug": "construccion", "name_es": "Construcción y remodelación", "name_en": "Construction & Remodeling", "license": "red"},
    {"sector": "hogar", "slug": "drywall", "name_es": "Drywall", "name_en": "Drywall", "license": "yellow"},
    {"sector": "hogar", "slug": "carpinteria", "name_es": "Carpintería", "name_en": "Carpentry", "license": "yellow"},
    {"sector": "hogar", "slug": "pisos", "name_es": "Pisos", "name_en": "Flooring", "license": "yellow"},
    {"sector": "hogar", "slug": "azulejos", "name_es": "Azulejos y cerámica", "name_en": "Tile & Ceramics", "license": "yellow"},
    {"sector": "hogar", "slug": "gabinetes", "name_es": "Instalación de gabinetes", "name_en": "Cabinet Installation", "license": "yellow"},
    {"sector": "hogar", "slug": "ventanas-puertas", "name_es": "Ventanas y puertas", "name_en": "Window & Door Installation", "license": "yellow"},
    {"sector": "hogar", "slug": "herreria", "name_es": "Herrería y metalwork", "name_en": "Ironwork & Metal", "license": "yellow"},
    {"sector": "hogar", "slug": "cercas", "name_es": "Cercas / Fencing", "name_en": "Fencing", "license": "yellow"},
    {"sector": "hogar", "slug": "concreto", "name_es": "Concreto y pavimento", "name_en": "Concrete & Paving", "license": "yellow"},
    {"sector": "hogar", "slug": "impermeabilizacion", "name_es": "Impermeabilización", "name_en": "Waterproofing", "license": "yellow"},
    {"sector": "hogar", "slug": "alarmas-camaras", "name_es": "Alarmas y cámaras", "name_en": "Security Systems", "license": "red"},
    {"sector": "hogar", "slug": "iluminacion", "name_es": "Instalación de iluminación", "name_en": "Lighting Installation", "license": "red"},
    {"sector": "hogar", "slug": "electrodomesticos", "name_es": "Reparación de electrodomésticos", "name_en": "Appliance Repair", "license": "yellow"},
    {"sector": "hogar", "slug": "garage-door", "name_es": "Puertas de garage", "name_en": "Garage Door Repair", "license": "yellow"},
    {"sector": "hogar", "slug": "mudanzas", "name_es": "Mudanzas locales", "name_en": "Local Moving", "license": "yellow"},
    {"sector": "hogar", "slug": "mudanzas-largo", "name_es": "Mudanzas de largo alcance", "name_en": "Long Distance Moving", "license": "red"},
    {"sector": "hogar", "slug": "demolicion", "name_es": "Demolición", "name_en": "Demolition", "license": "red"},
    {"sector": "hogar", "slug": "fumigacion", "name_es": "Fumigación", "name_en": "Pest Control", "license": "red"},
    {"sector": "hogar", "slug": "chinches", "name_es": "Exterminio de chinches", "name_en": "Bed Bug Extermination", "license": "red"},

    # SECTOR 2 — Jardinería y exteriores
    {"sector": "jardineria", "slug": "jardineria", "name_es": "Jardinería y yardwork", "name_en": "Landscaping", "license": "green"},
    {"sector": "jardineria", "slug": "arboles", "name_es": "Poda y tala de árboles", "name_en": "Tree Trimming & Removal", "license": "yellow"},
    {"sector": "jardineria", "slug": "diseno-jardines", "name_es": "Diseño de jardines", "name_en": "Garden Design", "license": "green"},
    {"sector": "jardineria", "slug": "sod", "name_es": "Instalación de pasto", "name_en": "Sod Installation", "license": "green"},
    {"sector": "jardineria", "slug": "riego", "name_es": "Sistema de riego", "name_en": "Irrigation & Sprinklers", "license": "yellow"},
    {"sector": "jardineria", "slug": "piscina", "name_es": "Mantenimiento de piscina", "name_en": "Pool Maintenance", "license": "yellow"},
    {"sector": "jardineria", "slug": "construccion-piscina", "name_es": "Construcción de piscina", "name_en": "Pool Construction", "license": "red"},
    {"sector": "jardineria", "slug": "deck-pergola", "name_es": "Deck y pergolas", "name_en": "Deck & Pergola", "license": "yellow"},
    {"sector": "jardineria", "slug": "pressure-washing", "name_es": "Limpieza con presión", "name_en": "Pressure Washing", "license": "green"},
    {"sector": "jardineria", "slug": "excavacion", "name_es": "Excavación", "name_en": "Excavation", "license": "red"},
    {"sector": "jardineria", "slug": "mantenimiento-propiedades", "name_es": "Mantenimiento de propiedades", "name_en": "Property Maintenance", "license": "green"},

    # SECTOR 3 — Mecánica y autos
    {"sector": "autos", "slug": "mecanica", "name_es": "Mecánica general", "name_en": "Auto Mechanic", "license": "yellow"},
    {"sector": "autos", "slug": "mecanica-domicilio", "name_es": "Mecánica a domicilio", "name_en": "Mobile Mechanic", "license": "yellow"},
    {"sector": "autos", "slug": "frenos", "name_es": "Frenos", "name_en": "Brake Service", "license": "yellow"},
    {"sector": "autos", "slug": "transmision", "name_es": "Transmisión", "name_en": "Transmission", "license": "yellow"},
    {"sector": "autos", "slug": "llantas", "name_es": "Llantas y rines", "name_en": "Tires & Rims", "license": "green"},
    {"sector": "autos", "slug": "pintura-autos", "name_es": "Pintura de autos", "name_en": "Auto Paint", "license": "yellow"},
    {"sector": "autos", "slug": "hojalateria", "name_es": "Hojalatería", "name_en": "Auto Body Work", "license": "yellow"},
    {"sector": "autos", "slug": "detailing", "name_es": "Detailing de autos", "name_en": "Auto Detailing", "license": "green"},
    {"sector": "autos", "slug": "ac-autos", "name_es": "A/C de autos", "name_en": "Auto A/C", "license": "yellow"},
    {"sector": "autos", "slug": "audio-autos", "name_es": "Car audio", "name_en": "Car Audio", "license": "green"},
    {"sector": "autos", "slug": "tinted-autos", "name_es": "Tintado de ventanas", "name_en": "Window Tinting", "license": "green"},
    {"sector": "autos", "slug": "cristales-autos", "name_es": "Cristales de auto", "name_en": "Auto Glass Repair", "license": "yellow"},
    {"sector": "autos", "slug": "grua", "name_es": "Grúa y remolque", "name_en": "Towing", "license": "red"},
    {"sector": "autos", "slug": "inspeccion-autos", "name_es": "Inspección de autos usados", "name_en": "Used Car Inspection", "license": "yellow"},
    {"sector": "autos", "slug": "seguro-auto", "name_es": "Seguros de auto", "name_en": "Auto Insurance", "license": "red"},
    {"sector": "autos", "slug": "lavado-autos", "name_es": "Lavado de autos a domicilio", "name_en": "Mobile Car Wash", "license": "green"},

    # SECTOR 4 — Servicios profesionales y financieros
    {"sector": "profesionales", "slug": "impuestos", "name_es": "Preparación de impuestos", "name_en": "Tax Preparation", "license": "red"},
    {"sector": "profesionales", "slug": "contabilidad", "name_es": "Contabilidad", "name_en": "Accounting & Bookkeeping", "license": "red"},
    {"sector": "profesionales", "slug": "notario", "name_es": "Notario público", "name_en": "Notary Public", "license": "red"},
    {"sector": "profesionales", "slug": "traduccion", "name_es": "Traducción e interpretación", "name_en": "Translation", "license": "green"},
    {"sector": "profesionales", "slug": "seguros", "name_es": "Agente de seguros", "name_en": "Insurance Agent", "license": "red"},
    {"sector": "profesionales", "slug": "bienes-raices", "name_es": "Bienes raíces", "name_en": "Real Estate", "license": "red"},
    {"sector": "profesionales", "slug": "hipotecas", "name_es": "Crédito e hipotecas", "name_en": "Mortgage & Loans", "license": "red"},
    {"sector": "profesionales", "slug": "credito", "name_es": "Reparación de crédito", "name_en": "Credit Repair", "license": "red"},
    {"sector": "profesionales", "slug": "consultoria", "name_es": "Consultoría de negocios", "name_en": "Business Consulting", "license": "green"},
    {"sector": "profesionales", "slug": "registro-llc", "name_es": "Registro de LLC", "name_en": "LLC Formation", "license": "yellow"},
    {"sector": "profesionales", "slug": "asistente-virtual", "name_es": "Asistente virtual", "name_en": "Virtual Assistant", "license": "green"},
    {"sector": "profesionales", "slug": "tramites", "name_es": "Trámites y gestiones", "name_en": "Document Services", "license": "green"},

    # SECTOR 5 — Salud y bienestar
    {"sector": "salud", "slug": "entrenamiento", "name_es": "Entrenamiento personal", "name_en": "Personal Training", "license": "yellow"},
    {"sector": "salud", "slug": "yoga", "name_es": "Yoga y meditación", "name_en": "Yoga & Meditation", "license": "green"},
    {"sector": "salud", "slug": "masajes", "name_es": "Masajes", "name_en": "Massage Therapy", "license": "red"},
    {"sector": "salud", "slug": "nutricion", "name_es": "Nutricionista", "name_en": "Nutritionist", "license": "red"},
    {"sector": "salud", "slug": "terapia-fisica", "name_es": "Terapia física", "name_en": "Physical Therapy", "license": "red"},
    {"sector": "salud", "slug": "enfermeria", "name_es": "Enfermería a domicilio", "name_en": "Home Nursing", "license": "red"},
    {"sector": "salud", "slug": "cuidado-heridas", "name_es": "Cuidado de heridas", "name_en": "Wound Care", "license": "red"},
    {"sector": "salud", "slug": "quiropractico", "name_es": "Quiropráctico", "name_en": "Chiropractor", "license": "red"},
    {"sector": "salud", "slug": "acupuntura", "name_es": "Acupuntura", "name_en": "Acupuncture", "license": "red"},
    {"sector": "salud", "slug": "psicologia", "name_es": "Psicología y terapia", "name_en": "Psychology & Therapy", "license": "red"},
    {"sector": "salud", "slug": "medicina-alternativa", "name_es": "Medicina alternativa", "name_en": "Alternative Medicine", "license": "yellow"},
    {"sector": "salud", "slug": "cuidado-mayores", "name_es": "Cuidado de personas mayores", "name_en": "Senior Care", "license": "yellow"},
    {"sector": "salud", "slug": "companero-mayores", "name_es": "Compañía para adultos mayores", "name_en": "Senior Companion", "license": "green"},
    {"sector": "salud", "slug": "asistencia-mayores", "name_es": "Asistencia en el hogar para mayores", "name_en": "Home Health Aide", "license": "red"},

    # SECTOR 6 — Belleza y estética
    {"sector": "belleza", "slug": "peluqueria", "name_es": "Peluquería", "name_en": "Hair Salon", "license": "red"},
    {"sector": "belleza", "slug": "barberia", "name_es": "Barbería", "name_en": "Barbershop", "license": "red"},
    {"sector": "belleza", "slug": "nails", "name_es": "Uñas / Nails", "name_en": "Nail Technician", "license": "red"},
    {"sector": "belleza", "slug": "maquillaje", "name_es": "Maquillaje", "name_en": "Makeup Artist", "license": "yellow"},
    {"sector": "belleza", "slug": "cejas-pestanas", "name_es": "Cejas y pestañas", "name_en": "Brows & Lashes", "license": "yellow"},
    {"sector": "belleza", "slug": "depilacion", "name_es": "Depilación", "name_en": "Waxing", "license": "yellow"},
    {"sector": "belleza", "slug": "spa", "name_es": "Spa y faciales", "name_en": "Spa & Facials", "license": "red"},
    {"sector": "belleza", "slug": "estilismo", "name_es": "Estilismo a domicilio", "name_en": "Mobile Stylist", "license": "red"},
    {"sector": "belleza", "slug": "maquillaje-eventos", "name_es": "Maquillaje para eventos", "name_en": "Bridal & Event Makeup", "license": "yellow"},
    {"sector": "belleza", "slug": "extensiones", "name_es": "Extensiones de cabello", "name_en": "Hair Extensions", "license": "red"},
    {"sector": "belleza", "slug": "bronceado", "name_es": "Bronceado", "name_en": "Spray Tan", "license": "yellow"},
    {"sector": "belleza", "slug": "tatuajes", "name_es": "Tatuajes", "name_en": "Tattoo Artist", "license": "red"},
    {"sector": "belleza", "slug": "piercings", "name_es": "Piercings", "name_en": "Piercing", "license": "red"},

    # SECTOR 7 — Cuidado infantil y educación
    {"sector": "educacion", "slug": "cuidado-ninos", "name_es": "Cuidado de niños", "name_en": "Childcare", "license": "red"},
    {"sector": "educacion", "slug": "ninera", "name_es": "Niñera / Babysitter", "name_en": "Babysitter", "license": "yellow"},
    {"sector": "educacion", "slug": "guarderia", "name_es": "Guardería en casa", "name_en": "Home Daycare", "license": "red"},
    {"sector": "educacion", "slug": "tutoria", "name_es": "Tutoría escolar", "name_en": "Academic Tutoring", "license": "green"},
    {"sector": "educacion", "slug": "clases-ingles", "name_es": "Clases de inglés", "name_en": "English Classes", "license": "green"},
    {"sector": "educacion", "slug": "clases-espanol", "name_es": "Clases de español", "name_en": "Spanish Classes", "license": "green"},
    {"sector": "educacion", "slug": "musica", "name_es": "Clases de música", "name_en": "Music Lessons", "license": "green"},
    {"sector": "educacion", "slug": "guitarra", "name_es": "Clases de guitarra", "name_en": "Guitar Lessons", "license": "green"},
    {"sector": "educacion", "slug": "piano", "name_es": "Clases de piano", "name_en": "Piano Lessons", "license": "green"},
    {"sector": "educacion", "slug": "baile", "name_es": "Clases de baile", "name_en": "Dance Classes", "license": "green"},
    {"sector": "educacion", "slug": "arte", "name_es": "Clases de arte", "name_en": "Art Classes", "license": "green"},
    {"sector": "educacion", "slug": "computacion", "name_es": "Clases de computación", "name_en": "Computer Classes", "license": "green"},
    {"sector": "educacion", "slug": "transporte-escolar", "name_es": "Transporte escolar", "name_en": "School Transportation", "license": "red"},

    # SECTOR 8 — Comida y catering
    {"sector": "comida", "slug": "catering", "name_es": "Catering para eventos", "name_en": "Event Catering", "license": "yellow"},
    {"sector": "comida", "slug": "chef-domicilio", "name_es": "Chef a domicilio", "name_en": "Private Chef", "license": "yellow"},
    {"sector": "comida", "slug": "reposteria", "name_es": "Pasteles y repostería", "name_en": "Cakes & Bakery", "license": "yellow"},
    {"sector": "comida", "slug": "comida-tradicional", "name_es": "Tamales y comida tradicional", "name_en": "Traditional Food", "license": "yellow"},
    {"sector": "comida", "slug": "meal-prep", "name_es": "Meal prep", "name_en": "Meal Prep", "license": "yellow"},
    {"sector": "comida", "slug": "bartending", "name_es": "Bartending", "name_en": "Bartending", "license": "red"},
    {"sector": "comida", "slug": "meseros", "name_es": "Meseros para eventos", "name_en": "Event Waitstaff", "license": "green"},
    {"sector": "comida", "slug": "food-truck", "name_es": "Food truck", "name_en": "Food Truck", "license": "red"},
    {"sector": "comida", "slug": "clases-cocina", "name_es": "Clases de cocina", "name_en": "Cooking Classes", "license": "green"},
    {"sector": "comida", "slug": "pinatas", "name_es": "Piñatas artesanales", "name_en": "Piñatas", "license": "green"},

    # SECTOR 9 — Eventos y entretenimiento
    {"sector": "eventos", "slug": "fotografia", "name_es": "Fotografía de eventos", "name_en": "Event Photography", "license": "green"},
    {"sector": "eventos", "slug": "videografia", "name_es": "Videografía", "name_en": "Videography", "license": "green"},
    {"sector": "eventos", "slug": "fotografia-quinceanera", "name_es": "Fotografía de quinceañeras", "name_en": "Quinceañera Photography", "license": "green"},
    {"sector": "eventos", "slug": "fotografia-bodas", "name_es": "Fotografía de bodas", "name_en": "Wedding Photography", "license": "green"},
    {"sector": "eventos", "slug": "fotografia-productos", "name_es": "Fotografía de productos", "name_en": "Product Photography", "license": "green"},
    {"sector": "eventos", "slug": "dj", "name_es": "DJ", "name_en": "DJ", "license": "green"},
    {"sector": "eventos", "slug": "mariachi", "name_es": "Mariachi y música en vivo", "name_en": "Mariachi & Live Music", "license": "green"},
    {"sector": "eventos", "slug": "animacion-fiestas", "name_es": "Animación de fiestas infantiles", "name_en": "Kids Party Entertainment", "license": "green"},
    {"sector": "eventos", "slug": "payasos-magos", "name_es": "Payasos y magos", "name_en": "Clowns & Magicians", "license": "green"},
    {"sector": "eventos", "slug": "brincolines", "name_es": "Renta de brincolines", "name_en": "Bounce House Rental", "license": "yellow"},
    {"sector": "eventos", "slug": "decoracion-eventos", "name_es": "Decoración de eventos", "name_en": "Event Decoration", "license": "green"},
    {"sector": "eventos", "slug": "planner-quinceanera", "name_es": "Organización de quinceañeras", "name_en": "Quinceañera Planning", "license": "green"},
    {"sector": "eventos", "slug": "planner-bodas", "name_es": "Organización de bodas", "name_en": "Wedding Planning", "license": "green"},
    {"sector": "eventos", "slug": "planner-eventos", "name_es": "Organización de eventos", "name_en": "Event Planning", "license": "green"},
    {"sector": "eventos", "slug": "flores", "name_es": "Flores y arreglos florales", "name_en": "Floral Arrangements", "license": "green"},
    {"sector": "eventos", "slug": "renta-mobiliario", "name_es": "Renta de sillas y mesas", "name_en": "Table & Chair Rental", "license": "green"},
    {"sector": "eventos", "slug": "carpas", "name_es": "Carpas y lonas", "name_en": "Tent & Canopy Rental", "license": "green"},
    {"sector": "eventos", "slug": "fotomaton", "name_es": "Fotomatón", "name_en": "Photo Booth", "license": "green"},

    # SECTOR 10 — Mascotas
    {"sector": "mascotas", "slug": "grooming", "name_es": "Peluquería de mascotas", "name_en": "Dog Grooming", "license": "green"},
    {"sector": "mascotas", "slug": "pet-sitting", "name_es": "Cuidado de mascotas", "name_en": "Pet Sitting", "license": "green"},
    {"sector": "mascotas", "slug": "dog-walking", "name_es": "Paseo de perros", "name_en": "Dog Walking", "license": "green"},
    {"sector": "mascotas", "slug": "entrenamiento-perros", "name_es": "Entrenamiento de perros", "name_en": "Dog Training", "license": "yellow"},
    {"sector": "mascotas", "slug": "veterinario", "name_es": "Veterinario a domicilio", "name_en": "Mobile Veterinarian", "license": "red"},
    {"sector": "mascotas", "slug": "hotel-mascotas", "name_es": "Hotel de mascotas", "name_en": "Pet Boarding", "license": "yellow"},
    {"sector": "mascotas", "slug": "fotografia-mascotas", "name_es": "Fotografía de mascotas", "name_en": "Pet Photography", "license": "green"},

    # SECTOR 11 — Tecnología y digital
    {"sector": "tecnologia", "slug": "reparacion-computadoras", "name_es": "Reparación de computadoras", "name_en": "Computer Repair", "license": "green"},
    {"sector": "tecnologia", "slug": "reparacion-celulares", "name_es": "Reparación de celulares", "name_en": "Phone Repair", "license": "green"},
    {"sector": "tecnologia", "slug": "redes-wifi", "name_es": "Instalación de redes WiFi", "name_en": "WiFi & Network Setup", "license": "green"},
    {"sector": "tecnologia", "slug": "soporte-tecnico", "name_es": "Soporte técnico a domicilio", "name_en": "In-Home Tech Support", "license": "green"},
    {"sector": "tecnologia", "slug": "diseno-web", "name_es": "Diseño web", "name_en": "Web Design", "license": "green"},
    {"sector": "tecnologia", "slug": "diseno-grafico", "name_es": "Diseño gráfico", "name_en": "Graphic Design", "license": "green"},
    {"sector": "tecnologia", "slug": "social-media", "name_es": "Redes sociales", "name_en": "Social Media Management", "license": "green"},
    {"sector": "tecnologia", "slug": "edicion-digital", "name_es": "Edición digital", "name_en": "Digital Photography & Editing", "license": "green"},
    {"sector": "tecnologia", "slug": "impresion", "name_es": "Impresión y diseño", "name_en": "Printing & Design", "license": "green"},
    {"sector": "tecnologia", "slug": "tv-sonido", "name_es": "Instalación de TV y sonido", "name_en": "TV & Sound Installation", "license": "green"},
    {"sector": "tecnologia", "slug": "smart-home", "name_es": "Smart home", "name_en": "Smart Home Setup", "license": "green"},

    # SECTOR 12 — Transporte y logística
    {"sector": "transporte", "slug": "transporte-medico", "name_es": "Transporte médico", "name_en": "Medical Transportation", "license": "yellow"},
    {"sector": "transporte", "slug": "transporte-aeropuerto", "name_es": "Transporte de aeropuerto", "name_en": "Airport Transportation", "license": "red"},
    {"sector": "transporte", "slug": "delivery", "name_es": "Mensajería y delivery local", "name_en": "Local Delivery", "license": "yellow"},
    {"sector": "transporte", "slug": "transporte-carga", "name_es": "Transporte de carga", "name_en": "Freight & Cargo", "license": "red"},
    {"sector": "transporte", "slug": "flete", "name_es": "Flete y acarreos", "name_en": "Hauling", "license": "yellow"},

    # SECTOR 13 — Ropa y textiles
    {"sector": "textiles", "slug": "costura", "name_es": "Costura y alteraciones", "name_en": "Sewing & Alterations", "license": "green"},
    {"sector": "textiles", "slug": "diseno-ropa", "name_es": "Diseño de ropa", "name_en": "Fashion Design", "license": "green"},
    {"sector": "textiles", "slug": "bordados", "name_es": "Bordados personalizados", "name_en": "Custom Embroidery", "license": "green"},
    {"sector": "textiles", "slug": "serigrafia", "name_es": "Serigrafía y estampados", "name_en": "Screen Printing", "license": "green"},
    {"sector": "textiles", "slug": "tintoreria", "name_es": "Limpieza en seco", "name_en": "Dry Cleaning", "license": "yellow"},
    {"sector": "textiles", "slug": "zapatero", "name_es": "Reparación de calzado", "name_en": "Shoe Repair", "license": "green"},

    # SECTOR 14 — Religiosos y culturales
    {"sector": "religioso", "slug": "musica-religiosa", "name_es": "Música religiosa", "name_en": "Religious Music", "license": "green"},
    {"sector": "religioso", "slug": "fotografia-religiosa", "name_es": "Fotografía de bautizos y comuniones", "name_en": "Baptism & Communion Photography", "license": "green"},
    {"sector": "religioso", "slug": "altares", "name_es": "Decoración de altares", "name_en": "Altar Decoration", "license": "green"},
    {"sector": "religioso", "slug": "limpia-espiritual", "name_es": "Limpia espiritual", "name_en": "Spiritual Cleansing", "license": "green"},
]

SECTOR_LABELS = {
    "hogar": "Hogar y mantenimiento",
    "jardineria": "Jardinería y exteriores",
    "autos": "Mecánica y autos",
    "profesionales": "Servicios profesionales y financieros",
    "salud": "Salud y bienestar",
    "belleza": "Belleza y estética",
    "educacion": "Cuidado infantil y educación",
    "comida": "Comida y catering",
    "eventos": "Eventos y entretenimiento",
    "mascotas": "Mascotas",
    "tecnologia": "Tecnología y digital",
    "transporte": "Transporte y logística",
    "textiles": "Ropa y textiles",
    "religioso": "Servicios religiosos y culturales",
}

SECTOR_COLORS = {
    "hogar": "#2F9D94",
    "jardineria": "#16A34A",
    "autos": "#0EA5E9",
    "profesionales": "#7C3AED",
    "salud": "#EF4444",
    "belleza": "#EC4899",
    "educacion": "#F59E0B",
    "comida": "#F97316",
    "eventos": "#A855F7",
    "mascotas": "#84CC16",
    "tecnologia": "#06B6D4",
    "transporte": "#475569",
    "textiles": "#DB2777",
    "religioso": "#0891B2",
}

# ─── Section 79 — Hierarchical category picker emojis ───────────────
# One emoji per sector (top-level "category") + per slug overrides for
# common subcategories. Anything not in SUBCATEGORY_EMOJIS falls back to
# its sector emoji. Emojis are stored on each category doc at startup so
# the UI can read them directly from `/api/categories` without a lookup.
SECTOR_EMOJIS = {
    "hogar":         "🏠",
    "jardineria":    "🌿",
    "autos":         "🚗",
    "profesionales": "💼",
    "salud":         "🩺",
    "belleza":       "💅",
    "educacion":     "🎓",
    "comida":        "🍽️",
    "eventos":       "🎉",
    "mascotas":      "🐾",
    "tecnologia":    "💻",
    "transporte":    "🚚",
    "textiles":      "👗",
    "religioso":     "🕊️",
}

# Per-subcategory overrides — kept compact, anything unlisted inherits
# the sector emoji. Picked the most recognizable ones for each domain.
SUBCATEGORY_EMOJIS = {
    # hogar
    "limpieza-hogar": "🧹", "limpieza-alfombras": "🧼", "limpieza-ventanas": "🪟",
    "limpieza-post-construccion": "🚧", "limpieza-comercial": "🏢",
    "organizacion-hogar": "🗂️", "lavanderia": "🧺",
    "plomeria": "🔧", "electricidad": "⚡", "hvac": "❄️",
    "techos": "🏚️", "pintura-interior": "🎨", "pintura-exterior": "🖌️",
    "construccion": "🏗️", "drywall": "🧱", "carpinteria": "🪚",
    "pisos": "🪵", "azulejos": "◽", "instalacion-gabinetes": "🪑",
    "ventanas-puertas": "🚪", "herreria": "🔩", "cercas": "🚧",
    "concreto": "🧱", "impermeabilizacion": "💧", "puertas-garage": "🏠",
    "demolicion": "💥", "excavacion": "🚜", "deck-pergolas": "🌳",
    "reparacion-electrodomesticos": "🔌", "mantenimiento-propiedades": "🏘️",
    "alarmas-camaras": "🚨", "instalacion-iluminacion": "💡",
    "fumigacion": "🐜", "exterminio-chinches": "🛏️",
    "smart-home": "🎛️", "instalacion-tv-sonido": "📺",
    # jardineria
    "jardineria-yardwork": "🌱", "poda-arboles": "🌳",
    "diseno-jardines": "🌷", "instalacion-pasto": "🌾",
    "sistema-riego": "💦", "mantenimiento-piscina": "🏊",
    "construccion-piscina": "🏖️", "limpieza-presion": "🚿",
    # autos
    "mecanica-general": "🔧", "mecanica-domicilio": "🏠",
    "frenos": "🛞", "transmision": "⚙️", "llantas-rines": "🛞",
    "pintura-autos": "🎨", "hojalateria": "🔨", "detailing-autos": "✨",
    "ac-autos": "❄️", "car-audio": "🔊", "tintado-ventanas": "🪟",
    "cristales-auto": "🪟", "grua-remolque": "🚚",
    "inspeccion-autos-usados": "🔍", "seguros-auto": "🛡️",
    "lavado-autos-domicilio": "🚿",
    # profesionales
    "impuestos": "📋", "contabilidad": "📊", "notario-publico": "📜",
    "traduccion": "🌐", "agente-seguros": "🛡️", "bienes-raices": "🏘️",
    "credito-hipotecas": "🏦", "reparacion-credito": "📈",
    "consultoria-negocios": "💡", "registro-llc": "📑",
    "asistente-virtual": "💻", "tramites-gestiones": "📨",
    # salud
    "entrenamiento-personal": "🏋️", "yoga-meditacion": "🧘",
    "masajes": "💆", "nutricionista": "🥗", "terapia-fisica": "🦴",
    "enfermeria-domicilio": "👩‍⚕️", "cuidado-heridas": "🩹",
    "quiropractico": "🦴", "acupuntura": "🪡",
    "psicologia-terapia": "🧠", "medicina-alternativa": "🌿",
    "cuidado-personas-mayores": "👵", "companía-adultos-mayores": "🤝",
    "asistencia-hogar-mayores": "🏠", "transporte-medico": "🚑",
    # belleza
    "peluqueria": "💇", "barberia": "💈", "unas": "💅",
    "maquillaje": "💄", "cejas-pestanas": "👁️", "depilacion": "🪒",
    "spa-faciales": "🧖", "estilismo-domicilio": "💇‍♀️",
    "maquillaje-eventos": "✨", "extensiones-cabello": "💁",
    "bronceado": "🌞", "tatuajes": "🖋️", "piercings": "💎",
    # educacion
    "tutoria-escolar": "📚", "clases-ingles": "🇺🇸",
    "clases-espanol": "🇲🇽", "clases-musica": "🎵",
    "clases-guitarra": "🎸", "clases-piano": "🎹",
    "clases-baile": "💃", "clases-arte": "🎨",
    "clases-computacion": "💻", "cuidado-ninos": "👶",
    "ninera": "👶", "guarderia-casa": "🏡", "transporte-escolar": "🚌",
    # comida
    "chef-domicilio": "👨‍🍳", "pasteles-reposteria": "🎂",
    "tamales-comida-tradicional": "🌮", "meal-prep": "🍱",
    "bartending": "🍸", "meseros-eventos": "🍽️",
    "food-truck": "🚚", "clases-cocina": "🍳",
    "pinatas-artesanales": "🪅",
    # eventos
    "fotografia-eventos": "📸", "videografia": "🎥",
    "fotografia-quinceaneras": "👑", "fotografia-bodas": "💒",
    "fotografia-productos": "📦", "dj": "🎧",
    "mariachi-musica-vivo": "🎺", "animacion-fiestas-infantiles": "🎈",
    "payasos-magos": "🤡", "renta-brincolines": "🎪",
    "decoracion-eventos": "🎀", "organizacion-quinceaneras": "👑",
    "organizacion-bodas": "💒", "organizacion-eventos": "📋",
    "flores-arreglos-florales": "💐", "renta-sillas-mesas": "🪑",
    "carpas-lonas": "⛺", "fotomaton": "📸",
    # mascotas
    "peluqueria-mascotas": "🐩", "cuidado-mascotas": "🐕",
    "paseo-perros": "🦮", "entrenamiento-perros": "🐕‍🦺",
    "veterinario-domicilio": "🩺", "hotel-mascotas": "🏨",
    "fotografia-mascotas": "📸",
    # tecnologia
    "reparacion-computadoras": "💻", "reparacion-celulares": "📱",
    "instalacion-redes-wifi": "📶", "soporte-tecnico-domicilio": "🛠️",
    "diseno-web": "🌐", "diseno-grafico": "🎨",
    "redes-sociales": "📲", "edicion-digital": "✂️",
    "impresion-diseno": "🖨️",
    # transporte
    "mudanzas-locales": "📦", "mudanzas-largo-alcance": "🚛",
    "flete-acarreos": "🚚", "transporte-carga": "📦",
    "mensajeria-delivery-local": "🛵", "transporte-aeropuerto": "✈️",
    # textiles
    "costura-alteraciones": "🧵", "diseno-ropa": "👗",
    "bordados-personalizados": "🪡", "serigrafia-estampados": "👕",
    "limpieza-seco": "🧥", "reparacion-calzado": "👞",
    # religioso
    "musica-religiosa": "⛪", "fotografia-bautizos-comuniones": "💒",
    "decoracion-altares": "🕯️", "limpia-espiritual": "🌿",
}


def emoji_for(slug: str, sector: str) -> str:
    """Resolve the best emoji for a subcategory slug — overrides win,
    otherwise fall back to the sector's emoji, otherwise a neutral tool."""
    return SUBCATEGORY_EMOJIS.get(slug) or SECTOR_EMOJIS.get(sector, "🛠️")


# 23 prioritized US cities by latino population
CITIES = [
    {"slug": "dallas", "name": "Dallas", "state": "TX"},
    {"slug": "houston", "name": "Houston", "state": "TX"},
    {"slug": "san-antonio", "name": "San Antonio", "state": "TX"},
    {"slug": "austin", "name": "Austin", "state": "TX"},
    {"slug": "el-paso", "name": "El Paso", "state": "TX"},
    {"slug": "fort-worth", "name": "Fort Worth", "state": "TX"},
    {"slug": "los-angeles", "name": "Los Ángeles", "state": "CA"},
    {"slug": "san-diego", "name": "San Diego", "state": "CA"},
    {"slug": "fresno", "name": "Fresno", "state": "CA"},
    {"slug": "san-jose", "name": "San José", "state": "CA"},
    {"slug": "miami", "name": "Miami", "state": "FL"},
    {"slug": "orlando", "name": "Orlando", "state": "FL"},
    {"slug": "tampa", "name": "Tampa", "state": "FL"},
    {"slug": "chicago", "name": "Chicago", "state": "IL"},
    {"slug": "new-york", "name": "Nueva York", "state": "NY"},
    {"slug": "phoenix", "name": "Phoenix", "state": "AZ"},
    {"slug": "las-vegas", "name": "Las Vegas", "state": "NV"},
    {"slug": "denver", "name": "Denver", "state": "CO"},
    {"slug": "charlotte", "name": "Charlotte", "state": "NC"},
    {"slug": "atlanta", "name": "Atlanta", "state": "GA"},
    {"slug": "sallisaw", "name": "Sallisaw", "state": "OK"},
    {"slug": "fort-smith", "name": "Fort Smith", "state": "AR"},
    {"slug": "tulsa", "name": "Tulsa", "state": "OK"},
]
